name: First Deployment
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    outputs:
      sentence: ${{steps.first-value.outputs.sentence}}
    runs-on: ubuntu-latest
    steps:
    - name: Print something
      id: first-value
      run: echo "This is my first time" >> write.txt "sentence = cat write.txt" >> $GITHUB.OUTPUT 
  another:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Print value from deploy
        run: cat ${{needs.deploy.outputs.sentence}}

